### ISSUE TITLE
Unexpected interaction with neon-animated-pages

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/paper-spinner#21] opened 2015-06-18 22:17 UTC
Maybe an edge case but ran into this today:

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">

<script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/iron-flex-layout/classes/iron-flex-layout.html">
<link rel="import" href="../bower_components/paper-spinner/paper-spinner.html">
<link rel="import" href="../bower_components/neon-animation/neon-animated-pages.html">
<link rel="import" href="../bower_components/neon-animation/neon-animatable.html">
<link rel="import" href="../bower_components/neon-animation/neon-animations.html">

<link rel="import" href="elements/elements.html">
</head>
<body unresolved class="fullbleed layout vertical">

  <template is="dom-bind" id="app">
    <neon-animated-pages id="pages" style="layout fit"
      selected="0"
      entry-animation='slide-from-right-animation'
      exit-animation='slide-left-animation'>

      <neon-animatable>
        page 1
      </neon-animatable>

      <neon-animatable>
        <paper-spinner active="{{loading}}"></paper-spinner>
      </neon-animatable>

    </neon-animated-pages>

  </template>

</body>
<script>
  var app = document.querySelector('#app');
  app.loading = false;

  window.addEventListener('WebComponentsReady', function() {
    setTimeout(function(){
      app.$.pages.selected = 1;
      app.loading = true;
    }, 2000);
  });
</script>
</html>
```

The idea is that when app.$.pages is set to transition it also activates the paper-spinner. However, paper-spinner receives an 'animationend' event on the transition, causing it's reset function to be called & this resets the spinner to be non-active.

**Comment by notwaldorf** [comment] 2015-07-27 12:35
Passing off to @morethanreal since I'm not super familiar with neon-animations

**Comment by keanulee** [comment] 2016-01-04 20:29
I tried to reproduce this issue but was unable to - since events bubble up, if `<neon-animatable>` fires an `animationend` event, `<paper-spinner>` shouldn't receive the event since it's a descendant.

http://jsbin.com/yisifazowe/1/edit?html,output

Going to close this issue; feel free to reopen if needed.

**Closed by keanulee** 2016-01-04 20:29 UTC
