### ISSUE TITLE
Spinner animation does not work normally after build

### ISSUE THREAD

**Issue by dgabrielli76** [PolymerElements/paper-spinner#51] opened 2016-06-10 15:34 UTC
### Description
I am using [gulp-htmlmin](https://github.com/jonschlinkert/gulp-htmlmin) to minify the HTML files of my application, but with the version 1.2.0 of the paper spinner, the animation does not work normally (see the Actual outcome section).
Into my gulp task `htmlmin` the rule that broke the animation is `minifyCSS` that is provided by [html-minifier](https://github.com/kangax/html-minifier).

Into the previous version of the spinner (`1.1.1`) everything was working perfectly.

### Expected outcome

The spinner animation should normally work.

### Actual outcome

![spinner-problem](https://cloud.githubusercontent.com/assets/9356931/15969416/57f3935c-2f30-11e6-823c-dfde9cc9f26a.gif)

**Comment by keanulee** [comment] 2016-06-13 18:23
Are you sure your minifier is properly handling CSS? If you inspect `<div id="spinnerContainer">`, do you see the `animation` property being set properly?

![image](https://cloud.githubusercontent.com/assets/1319720/16018415/3dc98eb6-3159-11e6-9515-84298f7090fa.png)

**Comment by dgabrielli76** [comment] 2016-06-14 08:14
Yes she seems to be set but obviously there is a problem, the warning says "invalid property value" (see below).
The thing I don't understand is why before the release 1.2.0 everything was working good?

<img width="887" alt="capture d ecran 2016-06-14 a 10 10 55" src="https://cloud.githubusercontent.com/assets/9356931/16035645/80375e26-3218-11e6-896c-0b42c709b165.png">

**Comment by LM450N** [comment] 2016-06-14 15:56
On the screen shot provided by @dgabrielli76, we can see there is no space between the time `1568ms` and the type `linear`. It still only to find why...

**Comment by keanulee** [comment] 2016-06-14 17:13
@LM450N is right - seems like the minifier isn't processing the value of `animation` properly (the space is necessary for the value to be valid). This didn't happen before 1.2.0 because the values were written in separate properties (e.g. `animation-name`, `animation-property`).

Closing since the provided CSS is valid and the problem is with the minifier.

**Closed by keanulee** 2016-06-14 17:13 UTC
Labels: p1 - backlog
